services:
  backend:
    build: ./server
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app
    environment:  
      - DATABASE_URL=postgres://postgres:password@db:5432/bathrooms
      - FRONTEND_URL=http://localhost:8080
    depends_on:
      - db

  frontend:
    build: ./client
    ports:
      - "8080:80"
    volumes:
      - ./client:/app
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000

  db:
    image: postgis/postgis:15-3.3
    container_name: postgres_container
    environment:  
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bathrooms
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  postgres-data: