services:
  web:
    build: ./server
    ports:
      - "5001:5001"
    environment:  
      - DATABASE_URL=postgres://postgres:password@db:5432/bathrooms
    depends_on:
      - db

  frontend:
    build: ./client
    ports:
      - "8080:80"

  db:
    image: postgres:15.3
    container_name: postgres_container
    environment:  
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bathrooms
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./tinkl.sql:/docker-entrypoint-initdb.d/tinkl.sql

volumes:
  postgres-data: