# Use Node.js as the base image
FROM node:22.6

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source code
COPY . .

# Build the TypeScript code
RUN npm run build

# Expose the server port
EXPOSE 5001

# Start the server using npm
CMD ["npm", "start"]