export interface BathroomType {
    id: number,
    api_id: string,
    name: string,
    street: string,
    city: string,
    state: string,
    accessible: boolean,
    unisex: boolean,
    directions: string | null,
    latitude: number,
    longitude: number,
    created_at: Date,
    updated_at: Date,
    country: string,
    changing_table: boolean,
    is_removed: boolean,
    is_single_stall: boolean,
    is_multi_stall: boolean,
    is_flagged: boolean,
    place_id: string,
    weekday_text: string | null,
    day_0_open: string | null,
    day_0_close: string | null,
    day_1_open: string | null,
    day_1_close: string | null,
    day_2_open: string | null,
    day_2_close: string | null,
    day_3_open: string | null,
    day_3_close: string | null,
    day_4_open: string | null,
    day_4_close: string | null,
    day_5_open: string | null,
    day_5_close: string | null,
    day_6_open: string | null,
    day_6_close: string | null,
    day_7_open: string | null,
    day_7_close: string | null,
    upvotes: number | null,
    downvotes: number | null
}